# Generated by Django 5.2.8 on 2025-11-23 04:24

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel_formacion', models.CharField(choices=[('CFT', 'CFT'), ('IP', 'IP'), ('U', 'U'), ('GEN', 'GEN')], max_length=3)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_responsables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='AsignacionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Jefe de área', 'Jefe de área'), ('Administrador', 'Administrador'), ('Editor de contenido', 'Editor de contenido')], max_length=30)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='operatividad.area')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_area', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Área',
                'verbose_name_plural': 'Asignaciones de Área',
                'unique_together': {('usuario', 'area')},
            },
        ),
        migrations.AddField(
            model_name='area',
            name='usuarios',
            field=models.ManyToManyField(related_name='areas', through='operatividad.AsignacionArea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('breve_descripcion', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('prioridad', models.PositiveSmallIntegerField(default=3)),
                ('tipo_contenido', models.CharField(choices=[('NOTICIA', 'Noticia'), ('EVENTO', 'Evento'), ('LOGRO', 'Logro'), ('OTRO', 'Otro')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicado', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('area_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contenidos_origen', to='operatividad.area')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'ordering': ['-prioridad', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='mural_adjuntos/')),
                ('tipo_archivo', models.CharField(blank=True, max_length=50)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='operatividad.contenido')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='AreaDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PUBLICADO', 'Publicado'), ('EN_ESPERA', 'En Espera'), ('EXPIRADO', 'Expirado')], max_length=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='operatividad.area')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='operatividad.contenido')),
            ],
            options={
                'verbose_name': 'Área Destinatario',
                'verbose_name_plural': 'Áreas Destinatarias',
                'unique_together': {('area', 'contenido')},
            },
        ),
    ]
