# Generated by Django 5.2.8 on 2025-12-31 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatividad', '0002_unique_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areadestinatario',
            name='fecha_asignacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
