# Generated by Django 5.2.8 on 2026-01-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatividad', '0003_alter_areadestinatario_fecha_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areadestinatario',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('EN_ESPERA', 'En Espera'), ('EXPIRADO', 'Expirado')], max_length=10),
        ),
    ]
