# Generated by Django 5.2.8 on 2026-01-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operatividad', '0004_alter_areadestinatario_estado'),
        ('operatividad', '0005_remove_fecha_publicado_from_contenido'),
    ]

    operations = [
    ]
