# Generated by Django 5.2.8 on 2026-03-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatividad', '0007_ubicacion_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='prioridad',
            field=models.BooleanField(default=False),
        ),
    ]
