"""
Django settings for CarreraConnect project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r^1up!5j&)8*xy9l6*qsd!(rk=_l3yqitknh9!6i@&%&xn)tpe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

BASE_URL = 'http://localhost:8000/'  # Cambia esto según tu configuración


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'operatividad',
    'mural',
]

# Use the default Django User model
AUTH_USER_MODEL = 'auth.User'

# Authentication backends: allow login by rut or correo_institucional
AUTHENTICATION_BACKENDS = [
    'CarreraConnect.auth_backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CarreraConnect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CarreraConnect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

LANGUAGES = [
    ('es-cl', 'Spanish (Chile)'),
]
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de subida de archivos
# Extensiones sin el punto, en minúsculas
# Por petición: limitar solo a PDF, audio/video y formatos de imagen.
# Solo permitir PDF e imágenes; prohibir multimedia (audio/video)
FILE_UPLOAD_ALLOWED_EXTENSIONS = [
    'pdf',
    # imágenes recomendadas
    'jpg', 'jpeg', 'png', 'gif', 'webp'
]

# Extensiones explícitamente prohibidas (incluye multimedia: audio/video)
FILE_UPLOAD_DISALLOWED_EXTENSIONS = [
    # ejecutables / instaladores / scripts / binarios
    'exe', 'msi', 'bat', 'cmd', 'sh', 'jar', 'apk', 'dmg', 'iso',
    'php', 'py', 'pl', 'rb', 'jsp', 'class', 'dll', 'so', 'js',
    'zip', 'rar', '7z',
    # audio (prohibidos)
    'mp3', 'wav', 'm4a', 'ogg', 'aac', 'flac', 'wma', 'aiff', 'opus',
    # video (prohibidos)
    'mp4', 'mkv', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mpg', 'mpeg',
    '3gp', 'm4v', 'ogv', 'mts', 'm2ts'
]

# Tamaño máximo por defecto en megabytes
FILE_UPLOAD_MAX_SIZE_MB = 20

# Tamaños por tipo (en MB). 
FILE_UPLOAD_MAX_SIZE_BY_TYPE = {
    'image': 10,
    'document': 20,
}

# Media files (archivos subidos por usuarios)
# `archivo.archivo.url` usará MEDIA_URL + name. Asegúrate de que la carpeta exista.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Permitir que la misma origen incruste recursos en iframe (necesario para previsualizar PDFs/embeds)
# En producción revisa esta configuración y usa cabeceras/CSP apropiadas.
X_FRAME_OPTIONS = 'SAMEORIGIN'

# URL de login para `login_required` y redirecciones
LOGIN_URL = '/operatividad/login/'

# URL donde se redirige tras login por defecto (puedes cambiar al nombre de la vista si prefieres)
LOGIN_REDIRECT_URL = '/operatividad/panel/'
# Vista personalizada para manejar errores CSRF y mostrar mensaje amigable al usuario
CSRF_FAILURE_VIEW = 'operatividad.views.csrf_failure'
SESSION_COOKIE_SAMESITE = 'Lax'     # o 'None' si realmente la cookie debe ser cross-site
CSRF_COOKIE_SAMESITE = 'Lax'
